# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code and the model into the container
COPY ./app ./app
COPY ./models ./models

# Expose the port the app runs on
EXPOSE 5000

# Define the command to run the app using gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app.main:app"]